title: Evan Haines
description: >
      University of Iowa, Tippie College of Business
      <br><br>
      M.S, Business Analytics
      <br><br>
      B.B.A, Business Analytics & Information Systems
      <br><br>
      Email: Evan-haines@uiowa.edu
      <br><br>
      Phone: (641) 919 3161
      <br><br>
      <a href="https://www.linkedin.com/in/evan-haines05">View LinkedIn Profile</a>   

      
logo: /images/headshot

theme: jekyll-theme-minimal
css: -/assets/custom.style.scss
