title: Evan Haines
description: University of Iowa, Tippie College of Business
description: M.S, Business Analytics
description: B.B.A, Business Analytics & Information Systems
#logo:
theme: jekyll-theme-minimal
