title: Evan Haines
description: University of Iowa, Tippie College of Business
             M.S, Business Analytics
             B.B.A, Business Analytics & Information Systems
logo: /images/headshot

theme: jekyll-theme-minimal


#social-network-links:
 # email: evan-haines@uiowa.edu
 # linkedin: https://www.linkedin.com/in/evan-haines05/

#share-links-active:
#  email: true
#  linkedin: true

